

services:
  frontend:
    build: ./frontend
      
    container_name: frontend_container
    restart: always
    ports:
      - "5173:5173"
    # volumes:
    #   - ./frontend:/app
    networks:
      - front-network
    depends_on:
      - backend

  backend:
    build: ./backend
      
    container_name: backend_container
    restart: always
    ports:
      - "8000:8000"
    env_file: "./backend/.env"
    # environment:
    #   - DB_CONNECTION=${DB_CONNECTION}
    #   - DB_HOST=${DB_HOST}
    #   - DB_PORT=${DB_PORT}
    #   - DB_DATABASE=${DB_DATABASE}
    #   - DB_USERNAME=${DB_USERNAME}
    #   - DB_PASSWORD=${DB_PASSWORD}

    command:  php artisan serve --host=0.0.0.0 --port=8000
    volumes:
      - ./backend:/app
    networks:
      - db-network
      - front-network
    depends_on:
      - mysql
 
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    env_file:
      - path : ./backend/.env
    ports:
      - 8080:8080
    networks:
      - db-network
    depends_on:
      - mysql
  mysql:
    image: mysql:9.2
    container_name: mysql_db
    ports:
      - "3306:3306"
    env_file:
      - path : ./backend/.env
    # environment:
    #   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    #   - MYSQL_DATABASE=${DB_NAME}
    #   - MYSQL_USER=${DB_USERNAME}
    #   - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./bdd/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - db-network

volumes:
  db_data:
networks:
  db-network:
  front-network:
  