name: "ESLint analysis"

on:
  push:
    branches:
      - linter
      - github-actions
  schedule:
    - cron: '45 15 * * 3' # Every Wednesday at 15:45 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run ESLint
        run: |
          cd frontend
          npx eslint build docs lib script spec-main -f node_modules/@microsoft/eslint-formatter-sarif/sarif.js -o results.sarif || true

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: frontend/results.sarif
