name: "ESLint analysis"

on:
  push:
    branches:
      - linter
      - github-actions
  schedule:
    - cron: '45 15 * * 3' # Every Wednesday at 15:45 UTC
permissions:
  actions: write
  contents: read
  security-events: write


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installer dépendances
        run: |
          cd frontend
          npm ci
      - name: Générer SARIF
        run: |
          cd frontend
          npx eslint "src/**/*.{js,svelte}" -f node_modules/@microsoft/eslint-formatter-sarif/sarif.js -o results.sarif || true
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: frontend/results.sarif
