name: "ESLint analysis"

on:
  push:
    branches:
      - linter
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installer les dépendances frontend
        run: |
          cd frontend
          npm install

      - name: Lister le contenu de frontend/src
        run: |
          ls -l frontend/src

      - name: Lancer ESLint sur src/
        run: |
          cd frontend
          npx eslint src --ext .js,.ts,.svelte -f node_modules/@microsoft/eslint-formatter-sarif/sarif.js -o ../results.sarif || true
          echo "Code retour ESLint : $?"
          ls -l ../results.sarif || echo "Pas de fichier SARIF généré"

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
