name: "ESLint analysis"

on:
  push:
    branches:
      - linter
      - github-actions
  schedule:
    - cron: '45 15 * * 3' # Every Wednesday at 15:45 UTC


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installer les dépendances
        run: |
          cd frontend
          npm ci

      - name: Lancer ESLint
        run: |
          cd frontend
          npx eslint "src/**/*.{js,svelte}" --format stylish

      # (Optionnel) Générer un rapport SARIF pour code scanning
      - name: Lancer ESLint (SARIF)
        run: |
          cd frontend
          npx eslint "src/**/*.{js,svelte}" -f node_modules/@microsoft/eslint-formatter-sarif/sarif.js -o ../results.sarif || true

      - name: Vérifier la présence du fichier SARIF
        run: ls -l results.sarif || echo "Pas de fichier SARIF généré"

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
